version: '3'
services:
  mysql:
    image: mariadb:latest
    environment:
      TZ: UTC-7
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_USER: ''
      MYSQL_PASSWORD: ''
      MYSQL_DATABASE: 'mtlkms'
    volumes:
      - ./mysqldata:/var/lib/mysql
    ports:
      - 3306:3306
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/host.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl/localhost.crt:/root/ssl/localhost.crt
      - ./nginx/ssl/localhost.key:/root/ssl/localhost.key
    network_mode: host
    ipc: host
    restart: unless-stopped     # or "always"
    command: /bin/sh -c "nginx -g 'daemon off;'"
  app:
    image: cuikho210/mtlkms:dev
    environment:
      DB_HOST: "mysql"
      DB_USER: ""
      DB_PASSWORD: ""
      SALT: ""
      EMAIL_PASSWORD: ""
      CLIENT_URL: "http://localhost:8080"
    ports:
      - 3000:3000
    links:
      - mysql
    volumes: # Only for dev, remove in prod
      - ./:/app