version: '3'
services:
  mysql:
    image: mariadb:latest
    environment:
      TZ: UTC-7
      MYSQL_ROOT_PASSWORD: '' # Your mysql root password
      MYSQL_USER: '' # Your mysql user
      MYSQL_PASSWORD: '' # Your mysql password
      MYSQL_DATABASE: 'mtlkms'
    volumes:
      - ./mysqldata:/var/lib/mysql
    ports:
      - 3306:3306
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/host.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl/localhost.crt:/root/ssl/localhost.crt # Your ssl file
      - ./nginx/ssl/localhost.key:/root/ssl/localhost.key # Change file name in /nginx/host.conf
    ports:
      - 80:80
      - 443:443
    links:
      - app:mtlkms
  app:
    image: cuikho210/mtlkms:amd64
    environment:
      DB_HOST: "mysql"
      DB_USER: "" # Equal MYSQL_USER
      DB_PASSWORD: "" # Equal MYSQL_PASSWORD
      SALT: "" # Any string
      EMAIL_PASSWORD: ""
      CLIENT_URL: "http://localhost:8080" # Your client URL
    links:
      - mysql
    volumes:
      - ./:/app
